const products = {
  list1: [
    {
      label: "Product 1",
      id: 1,
      amount: 9000,
      quantity: 1,
      description: "This is product 1",
      image: "",
    },
    {
      label: "Product 1",
      id: 2,
      amount: 9000,
      quantity: 1,
      description: "This is product 1",
      image: "",
    },
    {
      label: "Product 1",
      id: 3,
      amount: 9000,
      quantity: 1,
      description: "This is product 1",
      image: "",
    },
    {
      label: "Product 1",
      id: 4,
      amount: 9000,
      quantity: 1,
      description: "This is product 1",
      image: "",
    },
    {
      label: "Product 1",
      id: 5,
      amount: 9000,
      quantity: 1,
      description: "This is product 1",
      image: "",
    },
    {
      label: "Product 1",
      id: 6,
      amount: 9000,
      quantity: 1,
      description: "This is product 1",
      image: "",
    },
  ],
  list2: [
    {
      label: "Product 2",
      id: 7,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 8,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 9,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 10,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 11,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 12,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 13,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 14,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 15,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 16,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 17,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 18,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 19,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 20,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 21,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
  ],
};

export { products };
